### ISSUE TITLE
IntelliJ IDEA import gradle project doesn't appear in event logs

### ISSUE THREAD

**Issue by jer117** [corda/cordapp-tutorial#137]
I follow the tutorial, open the project and the event log doesn't show. "Click the ‘import gradle project’ link. Press OK on the dialogue that pops up Gradle will now download all the project dependencies and perform some indexing", step according the tutorial. I can compile corda outside of the IDEA but I would like to know the problem here. I can't seem to find any solution anywhere.

**Comment by joeldudley** [comment]
Yes, this has changed in IntelliJ 2018. You need to follow the updated instructions here: https://docs.corda.net/head/tutorial-cordapp.html#opening-the-example-cordapp-in-intellij.
