### ISSUE TITLE
cannot inline bytecode built with JVM Target 1.8 into that with 1.6?

### ISSUE THREAD

**Issue by Iangao25** [corda/cordapp-tutorial#141]
Hi there,

I was trying to run this example in IntelliJ, but the code 'vaultQueryBy<IOUState>' raised error that  'Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option'. 

I am a rookie in this area and hope can get this question solved. Thank you.

**Comment by joeldudley** [comment]
See https://stackoverflow.com/questions/48988778/cannot-inline-bytecode-built-with-jvm-target-1-8-into-bytecode-that-is-being-bui.
