### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by Sonal-Pal** [corda/cordapp-tutorial#142]
at com.example.NodeDriver.main(NodeDriver.java:32)
[quasar] ERROR: java/lang/Object
java.lang.IllegalArgumentException

At java:32
The code is : :
32 :        driver(new DriverParameters().withIsDebug(true).withWaitForAllNodesToFinish(true), dsl -> {
                    CordaFuture<NodeHandle> partyAFuture = dsl.startNode(new NodeParameters()
                            .withProvidedName(new CordaX500Name("PartyA", "London", "GB"))
                            .withRpcUsers(ImmutableList.of(user)));

**Comment by Sonal-Pal** [comment]
Please help me out

**Comment by manindra23** [comment]
I was getting exactly the same error. I was using jdk-10.0.1. When I switched to jdk1.8.0_171, it is working fine. I haven't figured out what in jdk-10.0.1 is causing the error.

**Comment by mikehearn** [comment]
You can't use Corda with Java 10. I'm surprised that even starts up. We will add more checks to block this.

**Comment by lightcap** [comment]
It'd be useful to note that Java 10 isn't supported. The docs just mention getting the latest version of Java (which is 10).

https://docs.corda.net/getting-set-up.html#id2
