### ISSUE TITLE
Unable to build the cordapp-example (Could not resolve bft-smart)

### ISSUE THREAD

**Issue by anshulee** [corda/cordapp-tutorial#154]
Am following the instructions from https://docs.corda.net/head/tutorial-cordapp.html. 
On doing gradle sync am getting a org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.github.bft-smart:library:master-v1.1-beta-g6215ec8-87.

When i hit https://jitpack.io/com/github/bft-smart/library/master-v1.1-beta-g6215ec8-87/library-master-v1.1-beta-g6215ec8-87.jar i get a "Build failed. See the log at jitpack.io" message
![buildfailed](https://user-images.githubusercontent.com/4685167/44944210-70248d00-adf0-11e8-8d58-df15773bbfaf.png)

**Comment by anshulee** [comment]
The build for /master-v1.1-beta-g6215ec8-87 is indeed failing since 30th August
https://jitpack.io/com/github/bft-smart/library/master-v1.1-beta-g6215ec8-87/build.log

Can we please refer another branch which isn't failing?/master-v1.1-beta-g34864da-135??

**Comment by adagys** [comment]
Thanks for reporting this, I've raised an issue with Jitpack – will see if they can rebuild it

**Comment by adagys** [comment]
This has been fixed in https://github.com/corda/cordapp-example/pull/155, if you pull the latest and wipe your Gradle cache it should work.
