### ISSUE TITLE
How to access web page for each node

### ISSUE THREAD

**Issue by Leungfranklin** [corda/cordapp-tutorial#54]
when I type http://localhost:xxx with the corresponding port xxxx, am I supposed to see a web page? In my case, I only see the message ''connection refused'.

**Comment by joeldudleyr3** [comment]
No - you have to go to /web/example. All web content is served on /web, and the subfolders beyond that are specified in staticServeDirs, here: https://github.com/corda/cordapp-tutorial/blob/master/kotlin-source/src/main/kotlin/com/example/plugin/ExamplePlugin.kt.
